### ISSUE TITLE
grpcio version issue

### ISSUE THREAD

**Issue by DongweiYe** [multiscale/muscle3#32]
Current muscle3 requires grpcio-1.17.1 version. However, the TensorFlow/Tensorborad requires grpcio-1.24.1 version. There is a conflict here.

**Comment by LourensVeen** [comment]
Ah, yes, that wouldn't work. I should check compatibility of grpcio, i.e. if you could use grpcio-1.24 with bindings generated by 1.17. Then we could widen the version requirements for MUSCLE 3, and be more compatible.

https://github.com/grpc/grpc/issues/17352 suggests that this should just work. Maybe we can try to force installation of grpcio-1.24 and see what happens?

**Comment by LourensVeen** [comment]
Okay, I've run the test suite with grpc 1.27.2 (the latest), 1.24.0, 1.22.0, and 1.20.0, and they all pass. Then I got curious and tried 1.0.0 (didn't install on Python 3), 1.8.1 (failed), 1.12.0 (failed, but less), 1.14.0 (failed), 1.14.2 (failed), 1.15.0 (passed) and 1.16.0 (passed).

So it seems that sometimes a version that's older than the version of grpcio-tools that was used to produce the bindings does work, but it's not a given. Since we don't have any issues with people needing to use older versions, I'll go and change the version requirement to 1.17.1 or higher but less than 2. That should fix tensorflow, and if there's another program that claims to require a lower version, then that program probably also actually doesn't, and should have its requirements fixed in the same way.

**Comment by LourensVeen** [comment]
Fixed in release 0.3.0.
