### ISSUE TITLE
Errors when running  reaction_diffusion_qmc.py

### ISSUE THREAD

**Issue by annakfg** [multiscale/muscle3#95]
I'm having problems with the coupling. Since the model configuration is similar to the reaction_diffusion_qmc.py problem, I decided to try. However, it doesn't work correctly. Basically, I am having the following types of errors for the model instance.

```
 File "/home/anna/.local/lib/python3.8/site-packages/libmuscle/mmp_client.py", line 165, in request_peers
    raise RuntimeError('Error getting peers from manager: {}'.format(
RuntimeError: Error getting peers from manager: Unknown kernel qmc
```

  ```
File "/home/anna/.local/lib/python3.8/site-packages/libmuscle/mcp/tcp_client.py", line 48, in __init__
    raise RuntimeError('Could not connect to the server at location'
RuntimeError: Could not connect to the server at location tcp:127.0.0.1:45733,[::1]:45733,139.30.91.179:45733,172.17.0.1:45733
```

```
File "/home/anna/.local/lib/python3.8/site-packages/libmuscle/runner.py", line 109, in implementation_process
    implementation()
RuntimeError: Could not connect to the server at location tcp:127.0.0.1:55621,[::1]:55621,139.30.91.179:55621,172.17.0.1:55621
```

I have no idea how to solve it. Did someone have the same problem and/or can help me with this?

I appreciate any help you can provide.

**Comment by LourensVeen** [comment]
Hi Anna,

Thanks for giving MUSCLE3 a try! It seems like there's an issue with the model description here, with the `qmc` component missing somehow. I'm not able to reproduce the error you are seeing with the reaction_diffusion_qmc.py script from the examples.

Can you post the complete script you're trying to run? And I assume you're using MUSCLE3 0.4.0, installed using pip?

**Comment by annakfg** [comment]
Hello,

Thank you for your response!
I'm running the code [docs/source/examples/python/reaction_diffusion_qmc.py](url) using the command `python3 reaction_diffusion_qmc.py`
Yes, I'm using the MUSCLE3 0.4.0 installed with pip; also, I'm not using any specific script because all the models are in the same file.

**Comment by LourensVeen** [comment]
Well, the funny thing is that the error message you're getting is generated when the component with the given name (`qmc` in this case) is missing from the model components. But the example at https://github.com/multiscale/muscle3/blob/develop/docs/source/examples/python/reaction_diffusion_qmc.py does have it, on line 247.

The only way I can think of that you're getting this error message is if your local file got changed, and doesn't match what I linked above. But since I can't see the file, I can't tell. If you don't want to paste the file, then you can check that each conduit goes from and to an existing component. (The next version of MUSCLE3 will check this a bit earlier and give a better error message.)

**Comment by LourensVeen** [comment]
You're welcome! And thanks for letting me know the outcome, so I don't have to worry about some unknown bug lurking somewhere. Please don't hesitate to make more issues if you run into any other problem.
